**Tips and Tricks**

In [2]:
import numpy as np

In [ ]:
a = np.random.randn(5) ## Rank 1 Array, Do not use this Rank 1 Array

In [11]:
a.shape ## Rank 1 Array, Do not use this Rank 1 Array

(5,)

In [17]:
a = np.random.randn(5,1) # commit to making it either a column vector or a row vector
# a = np.random.randn(1,5)

In [41]:
a= a.reshape((1,5))

In [43]:
a.shape

(1, 5)

In [45]:
assert(a.shape==(5,1))

AssertionError: 

In [35]:
a.shape

(5, 1)

**TRYING OUT THINGS**

In [10]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)

c=a*b

In [12]:
print(c)

[[ 0.29071214 -0.53846929 -0.86779795]
 [-0.90400902 -0.3420271  -0.41051948]
 [-0.16475037  0.22455381  0.43708738]]


In [6]:
a = np.random.randn(12288,50)
b = np.random.randn(150,45)

In [8]:
c = np.dot(a,b)

ValueError: shapes (12288,50) and (150,45) not aligned: 50 (dim 1) != 150 (dim 0)